Reported by: Alan (BrackDiesel@live.com)
Time       : Thu Dec 29 15:32:46 2011
Type       : runtime
Location   : ^EE/~v/upper_estate/Parva/Alan
*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.
Object: /domains/estates/virtual/boxes/Parva/Alan#124887 (/lib/items/get_from.c) at line 95

'<fake>' at /secure/save/players/a/alan (/<driver>) at line 0
'cmdAll' at /secure/save/players/a/alan (/lib/users/player.c) at line 1010
'cmdAll' at /secure/save/players/a/alan (/lib/livings/command.c) at line 44
'do_put_obj_word_obj' at /verbs/items/put at line 33
'eventPutInto' at /domains/estates/virtual/boxes/Parva/Alan#124887 (/lib/items/get_from.c) at line 95


Status     : NEW
Bug        : >
put 3rd ice axe in chest
You put an ice axe into a large wooden chest.
>
put 3rd ice axe in chest
You put an ice axe into a large wooden chest.
>
put 3rd ice axe in chest
You put an ice axe into a large wooden chest.
>
put 3rd ice axe in chest
You put an ice axe into a large wooden chest.
>
put 3rd ice axe in chest
A runtime error occurred, use "bug -r" to report it.

I was putting something that didnt exist in the chest. Probably the explaination for the runtime, this might be an id problem, such as stealing (which also has a problem with id's)
